const trackermodel = require('./db/modules/tracker.module');
const usermodel = require('./db/modules/user.module');
const authcontroller = require('./controller/auth.controller');
const authroutes = require('./routes/auth.routes');
const cors = require('cors');
const express = require('express');
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/auth', authroutes);
module.exports = app;